// Mongoose configuration file. For full list of build options, see
// https://mongoose.ws/docs/getting-started/build-options/

// DO NOT EDIT THIS FILE, BECAUSE CODE REGENERATION WILL DESTROY
// YOUR EDITS. THIS FILE INCLUDES THIS PROJECT'S main.h, SO
// INSTEAD, ADD BUILD OPTIONS TO Core/Inc/main.h

#pragma once

#define MG_ARCH MG_ARCH_CUBE
#define MG_ENABLE_FREERTOS 1
#define MG_ENABLE_TCPIP   0   /* НЕ используем встроенный стек Mongoose */
#define MG_ENABLE_LWIP    1   /* и его lwip-драйвер тоже нет           */
#define MG_ENABLE_SOCKET  1   /* едем поверх BSD-сокетов твоего LwIP   */
#define MG_ENABLE_POSIX_FS 0  /* файловой системы нет, страница в RAM  */
#define MG_MALLOC  pvPortMalloc
#define MG_FREE    vPortFree
